apiVersion: v1
kind: Service
metadata:
  name: {{ include "maven-hello-world.fullname" . }}
  labels:
    {{- include "maven-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "maven-hello-world.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer" }} 
  loadBalancerIP: ""
  {{- end }}
